<template>
  <section id="experience">
    <div class="inner">
      <div class="sec-label reveal"><span class="sec-num">[ 03 ]</span><span class="sec-line"></span><h2 class="sec-title">Mission <span>Log</span></h2></div>
      <div class="mlog">
        <div class="ms active reveal"><div class="ms-meta"><span class="ms-date">MAR 2025 — PRESENT · 1 YR 1 MO</span><span class="ms-org">BI TECHNOLOGY · FULL-TIME</span></div><div class="ms-title">Co-Founder &amp; CTO</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Riyadh, Saudi Arabia · On-site</span><span class="ms-badge">ACTIVE NOW</span></div><div class="ms-body">Building scalable SaaS platforms, AI solutions, and enterprise software. Leading software architecture, product development, and technical teams while developing strategic technology partnerships across the region.</div><div class="ms-skills"><span class="ms-sk">Project Management</span><span class="ms-sk">Team Leadership</span><span class="ms-sk">IT Service Management</span><span class="ms-sk">Strategic Partnerships</span><span class="ms-sk">Business Development</span></div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">NOV 2022 — AUG 2025 · 2 YRS 10 MOS</span><span class="ms-org">ALGHANIM INDUSTRIES — F&amp;B · FULL-TIME</span></div><div class="ms-title">Operation</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Riyadh, Saudi Arabia · On-site</span></div><div class="ms-body">Led operational functions within Alghanim's Food &amp; Beverage division — one of the region's largest conglomerates. Deepened expertise in large-scale enterprise operations, systems management, and technology integration.</div></div>
        <div class="ms reveal" style="opacity:.45"><div class="ms-meta"><span class="ms-date">MAY 2022 — OCT 2022 · 6 MOS</span><span class="ms-org">CAREER BREAK</span></div><div class="ms-title">Strategic Recharge</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Riyadh, Saudi Arabia</span><span class="ms-badge break">INTENTIONAL PAUSE</span></div><div class="ms-body">Intentional time for reflection, strategic planning, and preparing for the next phase of execution.</div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">NOV 2021 — APR 2022 · 6 MOS</span><span class="ms-org">JOULESLABS · FULL-TIME</span></div><div class="ms-title">Technical Project Manager</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Mirpur, Dhaka, Bangladesh</span></div><div class="ms-body">Managed end-to-end technical project delivery — coordinating engineering teams, defining milestones, and ensuring on-time product launches aligned with business objectives.</div><div class="ms-skills"><span class="ms-sk">Project Management</span></div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">NOV 2021 — APR 2022 · 6 MOS</span><span class="ms-org">CROWDFUNDLY · FULL-TIME</span></div><div class="ms-title">Technical Project Manager</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Dhaka, Bangladesh</span></div><div class="ms-body">Drove technical project execution at a fast-growing crowdfunding SaaS platform — bridging product vision with engineering delivery in an agile, high-velocity environment.</div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">SEP 2021 — OCT 2021 · 2 MOS</span><span class="ms-org">BKASH LIMITED · FULL-TIME</span></div><div class="ms-title">Customer Service Officer</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Dhaka, Bangladesh</span></div><div class="ms-body">Operated at the frontline of Bangladesh's leading mobile financial service — gaining deep insight into fintech operations, user pain points, and financial product workflows at scale.</div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">MAR 2021 — AUG 2021 · 6 MOS</span><span class="ms-org">SR SOFT · FULL-TIME</span></div><div class="ms-title">Project Manager (Technical)</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Dhaka, Bangladesh</span></div><div class="ms-body">Oversaw software delivery operations as Technical Project Manager — managing client requirements, development timelines, and team coordination across multiple concurrent projects.</div></div>
        <div class="ms reveal"><div class="ms-meta"><span class="ms-date">MAR 2020 — MAR 2021 · 1 YR 1 MO</span><span class="ms-org">BACKDOOR PRIVATE LTD. · FULL-TIME</span></div><div class="ms-title">Network Security Analyst</div><div class="ms-loc-wrap"><span class="ms-loc">◈ Dhaka, Bangladesh</span></div><div class="ms-body">Analyzed and fortified network security infrastructure — identifying vulnerabilities, implementing security protocols, and managing IT service continuity for enterprise clients across industries.</div><div class="ms-skills"><span class="ms-sk">IT Service Management</span><span class="ms-sk">Network Security</span><span class="ms-sk">Cybersecurity</span></div></div>
      </div>
    </div>
  </section>
</template>
